arch = "x64"
pt_path = 'D:\EDM115\Programmes\PowerToys'

[plugins.BrowserSearch]
repo = "TBM13/BrowserSearch"
version = "v1.8.0"

[plugins.ChatGPT]
repo = "ferraridavide/ChatGPTPowerToys"
version = "v0.86.0"

[plugins.ClipboardManager]
repo = "CoreyHayward/PowerToys-Run-ClipboardManager"
version = "v0.8.1"

[plugins.CurrencyConverter]
repo = "Advaith3600/PowerToys-Run-Currency-Converter"
version = "v1.3.0"

[plugins.Everything]
repo = "lin-ycv/EverythingPowerToys"
version = "v0.86.0"

[plugins.FastWeb]
repo = "CCcat8059/FastWeb"
version = "v1.5.3"

[plugins.GEmojiSharp]
repo = "hlaueriksson/GEmojiSharp"
version = "v4.0.1"

[plugins.GitHubRepo]
repo = "8LWXpg/PowerToysRun-GitHubRepo"
version = "v1.8.1"

[plugins.GitKraken]
repo = "davidegiacometti/PowerToys-Run-GitKraken"
version = "0.2.2"

[plugins.HexInspector]
repo = "NaroZeol/PowerHexInspector"
version = "v0.3.0"

[plugins.InputTyper]
repo = "CoreyHayward/PowerToys-Run-InputTyper"
version = "v0.2.0"

[plugins.ProcessKiller]
repo = "8LWXpg/PowerToysRun-ProcessKiller"
version = "v1.6.0"

[plugins.QuickLookup]
repo = "GTGalaxi/quick-lookup-ptrun"
version = "v1.3.3"

[plugins.SSH]
repo = "8LWXpg/PowerToysRun-SSH"
version = "v1.3.0"

[plugins.Spotify]
repo = "waaverecords/PowerToys-Run-Spotify"
version = "v0.86.0"

[plugins.UnicodeInput]
repo = "nathancartlidge/powertoys-run-unicode"
version = "v1.2.1"

[plugins.WebSearchShortcut]
repo = "Daydreamer-riri/PowerToys-Run-WebSearchShortcut"
version = "0.6.3"

[plugins.Winget]
repo = "bostrot/PowerToysRunPluginWinget"
version = "v1.3.0"
